import { Jogo } from "../types/tipos";

const ensureHttps = (url: string) => {
  if (!url) return 'https://via.placeholder.com/600x300/1a1a1a/ffffff?text=Imagem+Não+Disponível';
  return url.replace('http://', 'https://');
};

export const lojasMockadas: Record<string, string> = {
  '1': 'Steam',
  '2': 'Epic Games',
  '3': 'GOG',
  '4': 'Humble Store',
  '5': 'Fanatical',
  '6': 'Green Man Gaming',
  '7': 'Nuuvem',
  '8': 'GamersGate',
  '9': 'Microsoft Store',
  '10': 'PlayStation Store'
};

export const jogosMockados: Jogo[] = [
  {
    id: '1',
    titulo: 'The Witcher 3: Wild Hunt - Game of the Year Edition',
    precoAtual: 9.99,
    precoOriginal: 49.99,
    desconto: 80,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '93',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=abc123',
    releaseDate: '2016-08-30T00:00:00.000Z'
  },
  {
    id: '2',
    titulo: 'Red Dead Redemption 2',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '93',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=def456',
    releaseDate: '2019-12-05T00:00:00.000Z'
  },
  {
    id: '3',
    titulo: 'Cyberpunk 2077',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '21',
    lojaNome: 'Epic Games',
    avaliacao: 4.0,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '86',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=ghi789',
    releaseDate: '2020-12-10T00:00:00.000Z'
  },
  {
    id: '4',
    titulo: 'Elden Ring',
    precoAtual: 49.99,
    precoOriginal: 59.99,
    desconto: 17,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '96',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=jkl012',
    releaseDate: '2022-02-25T00:00:00.000Z'
  },
  {
    id: '5',
    titulo: 'Hogwarts Legacy',
    precoAtual: 49.99,
    precoOriginal: 59.99,
    desconto: 17,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.7,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '84',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=mno345',
    releaseDate: '2023-02-10T00:00:00.000Z'
  },
  {
    id: '6',
    titulo: 'Star Wars Jedi: Survivor',
    precoAtual: 39.99,
    precoOriginal: 69.99,
    desconto: 43,
    loja: '21',
    lojaNome: 'Epic Games',
    avaliacao: 4.5,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1774580/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '85',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=pqr678',
    releaseDate: '2023-04-28T00:00:00.000Z'
  },
  {
    id: '7',
    titulo: 'Resident Evil 4 Remake',
    precoAtual: 49.99,
    precoOriginal: 59.99,
    desconto: 17,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '93',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=stu901',
    releaseDate: '2023-03-24T00:00:00.000Z'
  },
  {
    id: '8',
    titulo: 'Dead Space Remake',
    precoAtual: 44.99,
    precoOriginal: 59.99,
    desconto: 25,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '89',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=vwx234',
    releaseDate: '2023-01-27T00:00:00.000Z'
  },
  {
    id: '9',
    titulo: 'Call of Duty: Modern Warfare II',
    precoAtual: 49.99,
    precoOriginal: 69.99,
    desconto: 29,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.2,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '79',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=yza567',
    releaseDate: '2022-10-28T00:00:00.000Z'
  },
  {
    id: '10',
    titulo: 'FIFA 23',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.1,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1811260/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '76',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=bcd890',
    releaseDate: '2022-09-30T00:00:00.000Z'
  },
  {
    id: '11',
    titulo: 'Destiny 2: Lightfall',
    precoAtual: 39.99,
    precoOriginal: 49.99,
    desconto: 20,
    loja: '21',
    lojaNome: 'Epic Games',
    avaliacao: 4.3,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '73',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=efg123',
    releaseDate: '2023-02-28T00:00:00.000Z'
  },
  {
    id: '12',
    titulo: "Marvel's Spider-Man Remastered",
    precoAtual: 49.99,
    precoOriginal: 59.99,
    desconto: 17,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '87',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=hij456',
    releaseDate: '2022-08-12T00:00:00.000Z'
  },
  {
    id: '13',
    titulo: 'God of War',
    precoAtual: 39.99,
    precoOriginal: 49.99,
    desconto: 20,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '93',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=klm789',
    releaseDate: '2022-01-14T00:00:00.000Z'
  },
  {
    id: '14',
    titulo: 'Stray',
    precoAtual: 24.99,
    precoOriginal: 29.99,
    desconto: 17,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.7,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1332010/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '83',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=nop012',
    releaseDate: '2022-07-19T00:00:00.000Z'
  },
  {
    id: '15',
    titulo: 'Forza Horizon 5',
    precoAtual: 39.99,
    precoOriginal: 59.99,
    desconto: 33,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '92',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=qrs345',
    releaseDate: '2021-11-09T00:00:00.000Z'
  },
  {
    id: '16',
    titulo: 'Halo Infinite',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.0,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '87',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=tuv678',
    releaseDate: '2021-12-08T00:00:00.000Z'
  },
  {
    id: '17',
    titulo: 'Sea of Thieves',
    precoAtual: 19.99,
    precoOriginal: 39.99,
    desconto: 50,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.5,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '69',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=wxy901',
    releaseDate: '2020-06-03T00:00:00.000Z'
  },
  {
    id: '18',
    titulo: 'Microsoft Flight Simulator',
    precoAtual: 59.99,
    precoOriginal: 69.99,
    desconto: 14,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.6,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '90',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=zab234',
    releaseDate: '2020-08-18T00:00:00.000Z'
  },
  {
    id: '19',
    titulo: 'Age of Empires IV',
    precoAtual: 39.99,
    precoOriginal: 59.99,
    desconto: 33,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.4,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1466860/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '82',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=cde567',
    releaseDate: '2021-10-28T00:00:00.000Z'
  },
  {
    id: '20',
    titulo: 'Grounded',
    precoAtual: 29.99,
    precoOriginal: 39.99,
    desconto: 25,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.3,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/962130/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '82',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=fgh890',
    releaseDate: '2022-09-27T00:00:00.000Z'
  },
  {
    id: '21',
    titulo: 'Psychonauts 2',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.7,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/607080/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '89',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=ijk123',
    releaseDate: '2021-08-25T00:00:00.000Z'
  },
  {
    id: '22',
    titulo: 'Ori and the Will of the Wisps',
    precoAtual: 19.99,
    precoOriginal: 29.99,
    desconto: 33,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1057090/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '90',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=lmn456',
    releaseDate: '2020-03-11T00:00:00.000Z'
  },
  {
    id: '23',
    titulo: 'Gears 5',
    precoAtual: 19.99,
    precoOriginal: 39.99,
    desconto: 50,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.2,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1097840/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '84',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=opq789',
    releaseDate: '2019-09-10T00:00:00.000Z'
  },
  {
    id: '24',
    titulo: 'State of Decay 2: Juggernaut Edition',
    precoAtual: 19.99,
    precoOriginal: 29.99,
    desconto: 33,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.1,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/495420/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '76',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=rst012',
    releaseDate: '2020-03-13T00:00:00.000Z'
  },
  {
    id: '25',
    titulo: 'The Outer Worlds',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.3,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/578650/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '82',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=uvw345',
    releaseDate: '2020-10-23T00:00:00.000Z'
  },
  {
    id: '26',
    titulo: 'Fallout 76',
    precoAtual: 9.99,
    precoOriginal: 39.99,
    desconto: 75,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 3.5,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1151340/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '52',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=xyz678',
    releaseDate: '2018-11-14T00:00:00.000Z'
  },
  {
    id: '27',
    titulo: 'The Elder Scrolls Online',
    precoAtual: 7.99,
    precoOriginal: 19.99,
    desconto: 60,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.0,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/306130/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '71',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=abc901',
    releaseDate: '2014-04-04T00:00:00.000Z'
  },
  {
    id: '28',
    titulo: 'DOOM Eternal',
    precoAtual: 19.99,
    precoOriginal: 59.99,
    desconto: 67,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.7,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '88',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=def234',
    releaseDate: '2020-03-20T00:00:00.000Z'
  },
  {
    id: '29',
    titulo: 'Wolfenstein II: The New Colossus',
    precoAtual: 9.99,
    precoOriginal: 59.99,
    desconto: 83,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.5,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/612880/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '87',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=ghi567',
    releaseDate: '2017-10-27T00:00:00.000Z'
  },
  {
    id: '30',
    titulo: 'Prey',
    precoAtual: 9.99,
    precoOriginal: 39.99,
    desconto: 75,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.4,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/480490/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '82',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=jkl890',
    releaseDate: '2017-05-05T00:00:00.000Z'
  },
  {
    id: '31',
    titulo: 'Dishonored 2',
    precoAtual: 9.99,
    precoOriginal: 39.99,
    desconto: 75,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.5,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/403640/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '86',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=mno123',
    releaseDate: '2016-11-11T00:00:00.000Z'
  },
  {
    id: '32',
    titulo: 'Deathloop',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.2,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1252330/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '88',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=pqr456',
    releaseDate: '2021-09-14T00:00:00.000Z'
  },
  {
    id: '33',
    titulo: 'Ghostwire: Tokyo',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.0,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1475810/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '77',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=stu789',
    releaseDate: '2022-03-25T00:00:00.000Z'
  },
  {
    id: '34',
    titulo: 'Hi-Fi Rush',
    precoAtual: 29.99,
    precoOriginal: 29.99,
    desconto: 0,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1817230/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '89',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=vwx012',
    releaseDate: '2023-01-25T00:00:00.000Z'
  },
  {
    id: '35',
    titulo: 'Starfield',
    precoAtual: 69.99,
    precoOriginal: 69.99,
    desconto: 0,
    loja: '8',
    lojaNome: 'Origin',
    avaliacao: 4.2,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '83',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=yza345',
    releaseDate: '2023-09-06T00:00:00.000Z'
  },
  {
    id: '36',
    titulo: 'Atomic Heart',
    precoAtual: 39.99,
    precoOriginal: 59.99,
    desconto: 33,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.1,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/668580/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '75',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=bcd678',
    releaseDate: '2023-02-21T00:00:00.000Z'
  },
  {
    id: '37',
    titulo: 'The Callisto Protocol',
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 3.9,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1544020/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '69',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=efg901',
    releaseDate: '2022-12-02T00:00:00.000Z'
  },
  {
    id: '38',
    titulo: 'Dead Island 2',
    precoAtual: 49.99,
    precoOriginal: 69.99,
    desconto: 29,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.3,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1943950/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '76',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=hij234',
    releaseDate: '2023-04-21T00:00:00.000Z'
  },
  {
    id: '39',
    titulo: 'Dying Light 2 Stay Human',
    precoAtual: 39.99,
    precoOriginal: 59.99,
    desconto: 33,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.2,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/534380/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '77',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=klm567',
    releaseDate: '2022-02-04T00:00:00.000Z'
  },
  {
    id: '40',
    titulo: 'Days Gone',
    precoAtual: 29.99,
    precoOriginal: 49.99,
    desconto: 40,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.4,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1259420/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '76',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=nop890',
    releaseDate: '2021-05-18T00:00:00.000Z'
  },
  {
    id: '41',
    titulo: 'Horizon Zero Dawn Complete Edition',
    precoAtual: 19.99,
    precoOriginal: 49.99,
    desconto: 60,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.7,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '84',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=qrs123',
    releaseDate: '2020-08-07T00:00:00.000Z'
  },
  {
    id: '42',
    titulo: "Marvel's Guardians of the Galaxy",
    precoAtual: 29.99,
    precoOriginal: 59.99,
    desconto: 50,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.6,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/1088850/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '80',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=tuv456',
    releaseDate: '2021-10-26T00:00:00.000Z'
  },
  {
    id: '43',
    titulo: 'Sekiro: Shadows Die Twice',
    precoAtual: 39.99,
    precoOriginal: 59.99,
    desconto: 33,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '90',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=wxy789',
    releaseDate: '2019-03-22T00:00:00.000Z'
  },
  {
    id: '44',
    titulo: 'Dark Souls III',
    precoAtual: 19.99,
    precoOriginal: 59.99,
    desconto: 67,
    loja: '1',
    lojaNome: 'Steam',
    avaliacao: 4.8,
    capa: ensureHttps('https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg'),
    plataformas: ['PC'],
    metacriticScore: '89',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=zab012',
    releaseDate: '2016-04-12T00:00:00.000Z'
  },
  {
    id: '45',
    titulo: 'Bloodborne',
    precoAtual: 19.99,
    precoOriginal: 19.99,
    desconto: 0,
    loja: '10',
    lojaNome: 'PlayStation Store',
    avaliacao: 4.9,
    capa: ensureHttps('https://image.api.playstation.com/vulcan/img/rnd/202010/2614/Y02gXKbjZe.png'),
    plataformas: ['PS4'],
    metacriticScore: '92',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=cde345',
    releaseDate: '2015-03-24T00:00:00.000Z'
  },
  {
    id: '46',
    titulo: "Demon's Souls",
    precoAtual: 69.99,
    precoOriginal: 69.99,
    desconto: 0,
    loja: '10',
    lojaNome: 'PlayStation Store',
    avaliacao: 4.8,
    capa: ensureHttps('https://image.api.playstation.com/vulcan/ap/rnd/202006/1014/T45iRN1bhiWcJUzST6UFGBvO.png'),
    plataformas: ['PS5'],
    metacriticScore: '92',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=fgh678',
    releaseDate: '2020-11-12T00:00:00.000Z'
  },
  {
    id: '47',
    titulo: 'Returnal',
    precoAtual: 69.99,
    precoOriginal: 69.99,
    desconto: 0,
    loja: '10',
    lojaNome: 'PlayStation Store',
    avaliacao: 4.5,
    capa: ensureHttps('https://image.api.playstation.com/vulcan/ap/rnd/202011/1021/TToUO5bxDm4i1YUdD3RqFDw7.png'),
    plataformas: ['PS5'],
    metacriticScore: '86',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=ijk901',
    releaseDate: '2021-04-30T00:00:00.000Z'
  },
  {
    id: '48',
    titulo: 'Ratchet & Clank: Rift Apart',
    precoAtual: 59.99,
    precoOriginal: 69.99,
    desconto: 14,
    loja: '10',
    lojaNome: 'PlayStation Store',
    avaliacao: 4.7,
    capa: ensureHttps('https://image.api.playstation.com/vulcan/ap/rnd/202011/0714/vuL88F9Yk5Rz8EEmd8Zy5YdX.png'),
    plataformas: ['PS5'],
    metacriticScore: '88',
    linkDeal: 'https://www.cheapshark.com/redirect?dealID=lmn234',
    releaseDate: '2021-06-11T00:00:00.000Z'
  }
];

export const getJogosPaginados = (pagina: number, jogosPorPagina: number, jogos: Jogo[]) => {
  const inicio = (pagina - 1) * jogosPorPagina;
  const fim = inicio + jogosPorPagina;
  return {
    jogos: jogos.slice(inicio, fim),
    totalPaginas: Math.ceil(jogos.length / jogosPorPagina),
    paginaAtual: pagina
  };
};